### ISSUE TITLE
Application Not Responding after adding duplicate task name

### ISSUE THREAD

**Issue by DieselGaming** [brit-hakrperson/Task_Manager#2]
When adding a new task, if you provide the task name to be that of one already created the program will not respond and eventually result in a JavaScript error.

## Expected Behavior
Either the original task is updated with the new information provided, or a new task with the same name is created with distinguishable identifiers.

## Current Behavior
After clicking save every other button/text field will not work, the program will load until Windows10 alerts the "Not Responding" state after which a JavaScript RangeError occurs.

## Possible Solution
Potential re-evaluation of the logic behind checking if a task already exists?

## Steps to Reproduce
1. Create a task like normal.
2. Create another task but use the same name as the task you just made.
3. Program does not respond to any other input.
4. Windows timeout - Not Responding.
5. JavaScript RangeError.

## Screenshots
![image](https://user-images.githubusercontent.com/44411085/166958597-6d565c47-3f62-4730-9d8e-ea624b4bf310.png)
![image](https://user-images.githubusercontent.com/44411085/166958621-d09054f5-42e9-461a-be79-793e1f4ac890.png)
![image](https://user-images.githubusercontent.com/44411085/166958652-de3d6beb-29d6-422d-9a37-55f4ad3e2ec7.png)

**Comment by brit-hakrperson** [comment]
this is a result of 2 issues:
 - bad error checking on form submit
 - bad CRUD handling

On submit, it either tried to update the task or tried to update a task with the taskname of ""
I have fixed both of the issues and am currently compiling a bugfix
